<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "abtestpages"
 *
 * Auto generated by Extension Builder 2017-09-07
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'AB Test Pages',
    'description' => 'Possibility to select an alternative page to show, instead of the current page.',
    'category' => 'misc',
    'author' => 'IllusionFACTORY',
    'author_email' => 'info@illusion-factory.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-8.7.99',
            'realurl' => '2.0.0-0.0.0'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'comment' => '',
    'user' => 'timof'
];
